language: java

jdk:
  - openjdk8

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

script:
  - ./mvnw clean verify -P${PROFILE:-ci}
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'

addons:
  sonarcloud:
    organization: "lflores"
    token:
      secure: "MgPDs7lCWrEgpUg86y8JhdOxR2wyVgYrVxcl1tTLu3f1lqi9O57GwvfLUtvTz1jYHrO7E1LjJmkPncspwJ4fJGfMFaJPsrOR0A2o2UyUlkcmBhaKlnSS+X4nVxyJ79P+EdW6o/QJoIy5lFPwPwNoIpCz1RwrZQkuAWFDeoPkFLZSIYdvcetsYFCzi6gff3iG6JAyLsNybIKGM6ukno7Sdjr6u2KvXHP8CqE4qbNCk/kR/os0bGGWd3XR6Ej5dE40wXe7eRo7LRzoPW2lmL6yXkRU74Uh+VPUIP2m6SyJbUTwdyhk7qMZnHVhOAlZvVbY8gjA+mHNWs+OPjW9Zy4rCGiI5TCjxZ69uwsNBi0yaThqRrAJwiNXYvw//HBRlq60H+WGYTONH25gZNBYbHFEhJjEGumo4MK0ttJn/+Pa4REuyCe94D+yGK7lCzXpf7wBYbW8VU82xrYr485OO8JAtJWNSfb+VoghG+C5GoduJ+QYffiDyk+FLbYuS4ANKKRajqk15GkElF4yD45mOCmANXCOYY2bzCNnocdxxj0UAVTPh9FTFrGIHvFR+J5w3J6OSUdaZfW13bKQVpMRrrrLWGpXzLxVjuQMGKDbdJSsshyMqmy0YMWdT8+DOYEf+xP9xLE3Ark1e5Hhx1/pZKveOZAyK6B8+0AEqsS8DKO9oPI="

