sudo: required
language: python
jdk:
  - oraclejdk8
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - jq --version
env:
  global:
    - DOCKER_REPO=com.triadsoft/tasks-api
    - ECS_APP_NAME=tasks-api
script:
  #- ./mvnw clean verify -P${PROFILE:-ci}
  - cd tasks-api
  - ./mvnw install dockerfile:build
deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: develop
cache:
  directories:
    - '$HOME/.m2/repository'

